class_name Terrain
extends Node3D

## Chunked terrain built from the height field, streamed around the player.
##
## The world is not stored anywhere: a chunk is generated from the seed when the
## player comes near and thrown away when they leave. That is what lets the world
## be large on a tablet — memory holds only what is currently in view.
##
## Detail drops with distance in rings. Because neighbouring rings sample the
## height field at different steps, their edges do not line up, so every chunk
## carries a skirt: a border of vertices dropped straight down. The crack is
## still there, it is simply behind a wall of ground-coloured geometry, which is
## far cheaper than stitching meshes together.

## Chunks built per frame while streaming. Low enough that walking never stutters.
## One at a time. Three chunks in a frame is three times the stutter in that
## frame — the total work is unchanged either way, but a child feels the pause,
## not the throughput. Ground fills in a little further behind them and nothing
## else is any different.
const CHUNKS_PER_FRAME := 1

## How many chunks may be baking at once, and how many finished bakes may be
## turned into nodes in a single frame.
##
## Baking moved off the main thread, but assembling did not: it is a mesh, two
## nodes and a shape, about a millisecond. Letting a burst of finished bakes
## all land in one frame would put a smaller version of the old hitch straight
## back, so they are spread out instead.
const BAKES_IN_FLIGHT := 3
const ASSEMBLED_PER_FRAME := 1

var field: HeightField

var _material: StandardMaterial3D
var _chunks: Dictionary = {}
var _queue: Array[Vector2i] = []

## Chunks that could stand to be coarser, done only when nothing is waiting.
var _lazy: Array[Vector2i] = []
var _centre := Vector2i(9999, 9999)

## Chunks currently being baked on a worker, by coordinate, and the finished
## bakes waiting to become nodes. The mutex guards only the handover list.
var _baking: Dictionary = {}
var _finished: Array = []
var _finished_mutex := Mutex.new()

## Bumped whenever the height field itself changes — which only a finished dam
## does. A bake started before that change describes ground that no longer
## exists, so anything stamped with an older generation is thrown away rather
## than assembled. Without this, damming the river while the chunks beside it
## were still baking would put the pre-dam riverbed back.
var _generation := 0

func _init(height_field: HeightField) -> void:
	field = height_field
	# Built here, not in _ready, so the terrain can be generated by a headless
	# check that never starts the scene tree.
	_material = StandardMaterial3D.new()
	# The terrain carries its biome in vertex colours, so one material covers
	# sand, grass, rock and snow without a single texture being loaded.
	_material.vertex_color_use_as_albedo = true
	# The tint colours are written as sRGB values, which is how they were picked.
	# Without this they are read as linear and the whole valley turns near-black.
	_material.vertex_color_is_srgb = true
	_material.roughness = 0.95
	_material.specular_mode = BaseMaterial3D.SPECULAR_DISABLED

## Draw the ground as flat vertex colour with no lighting. A diagnostic, not a
## look: it answers "are the colours wrong or is the light wrong", which are
## indistinguishable in a screenshot otherwise.
func set_unshaded(enabled: bool) -> void:
	_material.shading_mode = (
		BaseMaterial3D.SHADING_MODE_UNSHADED if enabled
		else BaseMaterial3D.SHADING_MODE_PER_PIXEL
	)

## Terrain follows the player rather than the player asking for terrain, so
## nothing else in the game has to know that the world is streamed.
func follow(world_position: Vector3) -> void:
	var chunk := TerrainSpec.chunk_at(world_position)
	if chunk == _centre:
		return
	_centre = chunk
	_rebuild_queue()

func _rebuild_queue() -> void:
	var wanted: Dictionary = {}
	var max_radius: int = TerrainSpec.RINGS[TerrainSpec.RINGS.size() - 1]["radius"]
	for dz in range(-max_radius, max_radius + 1):
		for dx in range(-max_radius, max_radius + 1):
			var coord := _centre + Vector2i(dx, dz)
			var ring := TerrainSpec.ring_for(maxi(absi(dx), absi(dz)))
			if ring < 0:
				continue
			wanted[coord] = ring

	# Drop what fell out of range before adding, so memory never spikes.
	for coord in _chunks.keys():
		if not wanted.has(coord):
			_chunks[coord].queue_free()
			_chunks.erase(coord)

	_queue.clear()
	_lazy.clear()

	# A chunk is rebuilt when it needs to become *better*: finer, or carrying
	# collision it does not have. It is not rebuilt merely to become coarser.
	#
	# Rings are measured from the player, so crossing a single chunk boundary
	# changes the ring of about seventy-six of the three hundred and sixty-one
	# chunks in range. Rebuilding all of them cost 76 x 19 ms — well over a
	# second of stutter — every sixty-four metres walked, and the queue had
	# barely drained before the next boundary arrived. Most of that work was to
	# make ground the player had just walked past *less* detailed, which nobody
	# has ever wanted done urgently.
	var pending: Array[Vector2i] = []
	for coord in wanted.keys():
		var existing = _chunks.get(coord)
		if existing == null:
			pending.append(coord)
			continue
		var ring: int = wanted[coord]
		var wants_step: int = TerrainSpec.RINGS[ring]["step"]
		var wants_collision: bool = TerrainSpec.RINGS[ring]["collide"]
		if wants_step < existing.step or (wants_collision and not existing.has_collision):
			pending.append(coord)
		elif existing.ring != ring:
			# Worth coarsening eventually, so the world does not slowly fill up
			# with fine meshes the player has wandered away from — but only when
			# there is nothing more urgent to do.
			_lazy.append(coord)

	# Nearest first: the ground under the player must exist before scenery does.
	pending.sort_custom(func(a: Vector2i, b: Vector2i) -> bool:
		return (a - _centre).length_squared() < (b - _centre).length_squared())
	_queue = pending
	# Furthest first when coarsening, since those are the ones costing the most
	# for the least.
	_lazy.sort_custom(func(a: Vector2i, b: Vector2i) -> bool:
		return (a - _centre).length_squared() > (b - _centre).length_squared())

func _process(_delta: float) -> void:
	_assemble_finished()

	# Only so many chunks in flight at once. Baking is off the main thread, but
	# a phone has few cores and the game still needs some of them.
	var in_flight := _baking.size()
	if in_flight >= BAKES_IN_FLIGHT:
		return

	# When there is nothing urgent, spend the frame coarsening one chunk that
	# the player has left behind.
	if _queue.is_empty() and not _lazy.is_empty():
		var stale: Vector2i = _lazy.pop_front()
		var offset := stale - _centre
		var ring := TerrainSpec.ring_for(maxi(absi(offset.x), absi(offset.y)))
		if ring >= 0 and _chunks.has(stale):
			_submit_chunk(stale, ring)
		return

	var started := 0
	while (
		started < CHUNKS_PER_FRAME
		and in_flight + started < BAKES_IN_FLIGHT
		and not _queue.is_empty()
	):
		var coord: Vector2i = _queue.pop_front()
		var ring := TerrainSpec.ring_for(maxi(absi(coord.x - _centre.x), absi(coord.y - _centre.y)))
		if ring < 0:
			continue
		_submit_chunk(coord, ring)
		started += 1

## True when every chunk in range has been built. The screenshot tool waits on
## this instead of guessing a frame count, so a capture never photographs a
## half-generated world.
func is_idle() -> bool:
	return _queue.is_empty() and _baking.is_empty() and _finished.is_empty()

## True once the ground the player is standing on is guaranteed to exist.
func has_ground_at(world_position: Vector3) -> bool:
	return _chunks.has(TerrainSpec.chunk_at(world_position))

## Rebuild the chunks within `radius` of a point, because the ground there has
## changed. Used when a dam is finished — the only thing in the game that edits
## the height field after generation.
##
## Only the affected chunks, not all 361: a full rebuild takes several seconds
## of streaming, during which the valley is visibly missing. A dam changes about
## forty metres of river, which is a handful of chunks.
##
## The chunks are dropped and re-queued rather than re-meshed in place, because
## each owns a HeightMapShape3D as well as a mesh and the existing build path
## does both.
func rebuild_near(world_position: Vector3, radius: float) -> void:
	# Everything already baking describes the ground as it was a moment ago.
	_generation += 1

	var affected: Array[Vector2i] = []
	for coord in _chunks.keys():
		var centre := Vector3(
			(float(coord.x) + 0.5) * TerrainSpec.CHUNK_SIZE,
			0.0,
			(float(coord.y) + 0.5) * TerrainSpec.CHUNK_SIZE
		)
		var flat := Vector2(centre.x - world_position.x, centre.z - world_position.z)
		if flat.length() > radius + TerrainSpec.CHUNK_SIZE:
			continue
		affected.append(coord)

	for coord in affected:
		_chunks[coord].queue_free()
		_chunks.erase(coord)
		if not _queue.has(coord):
			_queue.append(coord)

	# Nearest first, so the ground under the player comes back before the far
	# bank does.
	_queue.sort_custom(func(a: Vector2i, b: Vector2i) -> bool:
		return (a - _centre).length_squared() < (b - _centre).length_squared())

## Start a chunk on a worker thread. The ground appears a frame or two later
## than it used to; nothing waits for it here.
func _submit_chunk(coord: Vector2i, ring: int) -> void:
	if _baking.has(coord):
		return
	var step: int = TerrainSpec.RINGS[ring]["step"]
	var collide: bool = TerrainSpec.RINGS[ring]["collide"]
	_baking[coord] = {
		"ring": ring,
		"collide": collide,
		"generation": _generation,
		"task": WorkerThreadPool.add_task(
			_bake_on_worker.bind(coord, step, collide, _generation), true,
			"aava terrain chunk"
		),
	}

## Runs on a worker thread. Nothing here touches the scene tree, and the height
## field it reads writes nothing back — see HeightField's constructor.
func _bake_on_worker(coord: Vector2i, step: int, collide: bool, generation: int) -> void:
	var baked := TerrainChunk.bake(field, coord, step, collide)
	baked["generation"] = generation
	_finished_mutex.lock()
	_finished.append(baked)
	_finished_mutex.unlock()

## Assemble whatever the workers have finished. Cheap — a mesh, two nodes and a
## shape — and deliberately capped, so a burst of finished bakes cannot put the
## whole hitch back in one frame.
func _assemble_finished() -> void:
	var stamp := PerfLog.stamp()
	_assemble_finished_now()
	PerfLog.note("chunk build", stamp)

func _assemble_finished_now() -> void:
	var ready_now: Array = []
	_finished_mutex.lock()
	while not _finished.is_empty() and ready_now.size() < ASSEMBLED_PER_FRAME:
		ready_now.append(_finished.pop_front())
	_finished_mutex.unlock()

	for baked in ready_now:
		var coord: Vector2i = baked["coord"]
		var job = _baking.get(coord)
		_baking.erase(coord)
		if job == null:
			# The chunk went out of range while it was baking. Its work is
			# thrown away rather than added to a world nobody is looking at.
			continue
		WorkerThreadPool.wait_for_task_completion(job["task"])
		if int(baked["generation"]) != _generation:
			# The ground changed under this bake. Ask for it again rather than
			# showing the river where the pond now is.
			if not _queue.has(coord):
				_queue.append(coord)
			continue

		var previous = _chunks.get(coord)
		if previous != null:
			previous.queue_free()
		var chunk := TerrainChunk.new(baked, job["ring"], _material, job["collide"])
		add_child(chunk)
		_chunks[coord] = chunk
